# config file for dfareporting programs.

postgres:
  host: server_name
  port: 5432
  database: database_name
  username: user_name
  password: user_password
  insert_table: schema.table_name
  col_num: 00 # select count(*) from information_schema.columns where table_name='schema.table_name' and table_schema = 'schema';